grimorio/fichas/urls.py
from django.urls import path, include
from fichas.views import ListarFichas, CriarFichas, EditarFichas, DeletarFichas, DetalhesFichas, FichasAPI
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'fichas', FichasAPI)

urlpatterns = [
    path('', ListarFichas.as_view(), name='listar-fichas'),
    path('novo/', CriarFichas.as_view(), name = 'criar-fichas'),
    path('<int:pk>/', DetalhesFichas.as_view(), name = 'detalhe-fichas'),
    path('editar/<int:pk>/', EditarFichas.as_view(), name = 'editar-fichas'),
    path('deletar/<int:pk>', DeletarFichas.as_view(), name = 'deletar-fichas'),
    path('api/', include(router.urls)),
]

grimorio/grimorio/urls.py
from django.contrib import admin
from django.urls import path, include
from grimorio.views import Login, Logout, LoginAPI
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', Login.as_view(), name='index'),
    path('autenticacao-api/',LoginAPI.as_view()),
    path('admin/', admin.site.urls),
    path('logout/', Logout.as_view(),name='logout'),
    path('item/', include('itens.urls'), name='itens'),
    path('bestiario/', include('bestiario.urls'), name='bestiario'),
    path('fichas/',include('fichas.urls'), name="fichas")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

grimorio/itens/urls.py
from django.urls import path, include
from itens.views import ListarItens,  CriarItens, EditarItens, DeletarItens, DetalhesItens, ItensAPI
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'items', ItensAPI)

urlpatterns = [
    path('', ListarItens.as_view(), name='listar-itens'),
    path('novo/', CriarItens.as_view(), name = 'criar-itens'),
    path('<int:pk>/', DetalhesItens.as_view(), name = 'detalhes-itens'),
    path('editar/<int:pk>/', EditarItens.as_view(), name = 'editar-itens'),
    path('deletar/<int:pk>', DeletarItens.as_view(), name = 'deletar-itens'),
    path('api/', include(router.urls)),
]

grimorio/fichas/models.py
from django.db import models
from fichas.consts import OPCOES_CLASSE, OPCOES_ELEMENTO

class Ficha(models.Model):
    nome = models.CharField(max_length=100)
    nivel = models.SmallIntegerField(default=1)
    experiencia = models.SmallIntegerField(default=0)
    doragos = models.SmallIntegerField(default=0)
    classe = models.SmallIntegerField(choices=OPCOES_CLASSE,default=0)
    elemento = models.SmallIntegerField(choices=OPCOES_ELEMENTO,default=0)
    foto = models.ImageField(blank=True, null=True, upload_to='fichas/fotos')
    equipamento = models.TextField(blank=True, null=True)
    feiticos = models.TextField(blank=True, null=True)

    def __str__(self):
        return '{0} - {1}'.format(
            self.nome,
            self.get_classe_display()
        )

    def get_nome_classe(self):
        for codigo, nome in OPCOES_CLASSE:
            if self.classe == codigo:
                return nome
        return None

    def get_nome_elemento(self):
        for codigo, nome in OPCOES_ELEMENTO:
            if self.elemento == codigo:
                return nome
        return None

grimorio/fichas/forms.py
from django import forms
from fichas.models import Ficha

class FormularioFicha(forms.ModelForm):

    class Meta:
        model = Ficha
        exclude = []

grimorio/fichas/views.py
from grimorio.bibliotecas import LoginObrigatorio
from django.shortcuts import render
from django.views.generic import View, ListView, CreateView, UpdateView, DeleteView, DetailView
from fichas.models import Ficha
from fichas.forms import FormularioFicha
from fichas.serializers import FichaSerializer
from django.urls import reverse_lazy
from rest_framework import viewsets

class ListarFichas(ListView):

    model = Ficha
    context_object_name = 'fichas'
    template_name = 'fichas/listar.html'

    def get_queryset(self, **kwargs):
        queryset =  Ficha.objects.all()
        pesquisa = self.request.GET.get('pesquisa', None)
        if pesquisa is not None:
            query = queryset.filter(modelo_icontains=pesquisa)

        return queryset
    
class DetalhesFichas(DetailView):

    model = Ficha
    template_name = 'fichas/detalhes.html'
    context_object_name = 'ficha'

class CriarFichas(CreateView):

    model = Ficha
    form_class = FormularioFicha
    template_name = 'fichas/novo.html'
    success_url = reverse_lazy('listar-fichas')

class EditarFichas(UpdateView):
    model = Ficha
    form_class = FormularioFicha
    template_name = 'fichas/editar.html'
    success_url = reverse_lazy('listar-fichas')

class DeletarFichas(DeleteView):
    model = Ficha
    template_name = 'fichas/deletar.html'
    success_url = reverse_lazy('listar-fichas')

class FichasAPI(viewsets.ModelViewSet):
    queryset = Ficha.objects.all()
    serializer_class = FichaSerializer

grimorio/templates/fichas/deletar.html
{% extends "../base.html" %}

    {% block titulo %} Deletar Ficha{% endblock %}
    
    {% block content %}
    <form action = '/fichas/deletar/{{ object.pk}}' method="post">
        {% csrf_token %}

        <center>
            <div class = "alert alert-danger" role = 'alert'>
                <p>Tem certeza que deseja excluir a ficha "{{ object }} ?"</p>
            </div>
            <input type="submit" value="Confirmar" class="btn btn-danger" />
        </center>

    </form>

    {% endblock %}

grimorio/templates/fichas/detalhes.html
{% extends "../base.html" %}

{% block titulo %} Detalhes da Ficha {% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="card">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ ficha.foto.url }}" class="card-img-top" alt="Imagem da Ficha">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h1 class="card-title">{{ ficha.nome }}</h1>
                    <p class="card-text"><strong>Nível:</strong> {{ ficha.nivel }}</p>
                    <p class="card-text"><strong>Experiência:</strong> {{ ficha.experiencia }}</p>
                    <p class="card-text"><strong>Doragos:</strong> {{ ficha.doragos }}</p>
                    <p class="card-text"><strong>Classe:</strong> {{ ficha.get_classe_display }}</p>
                    <p class="card-text"><strong>Elemento:</strong> {{ ficha.get_elemento_display }}</p>
                    <p class="card-text"><strong>Equipamento:</strong> {{ ficha.equipamento|linebreaks }}</p>
                    <p class="card-text"><strong>Feitiços:</strong> {{ ficha.feiticos|linebreaks }}</p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a class="btn btn-warning me-md-2" href='/fichas/editar/{{ ficha.id }}' type="button">Editar</a>
                        <a class="btn btn-danger" href='/fichas/deletar/{{ ficha.id }}' type="button">Deletar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

grimorio/templates/fichas/editar.html
{% extends "../base.html" %}

    {% block titulo %} Editar Ficha{% endblock %}
    
    {% block content %}
        
        
        <div class="container mt-5">
            <h1 class="mb-4">Editar Ficha</h1>
            <form action = '/fichas/editar/{{ object.pk }}/' method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field }}
                        {% if field.errors %}
                            <div class="alert alert-danger mt-2">
                                {% for error in field.errors %}
                                    <p class="mb-0">{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
        

    {% endblock %}

grimorio/templates/fichas/listar.html
{% extends "../base.html" %}
{% block css_local %}
<style>
    .card-img-top {
        height: 200px;
        object-fit: cover;
    }
</style>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        
        <!-- Insira aqui a barra de pesquisa -->

        <div class="row">
            {% for ficha in fichas %}
            <div class="col-md-4">
                <div class="card mb-4">
                    {% if ficha.foto %}
                    <img src="{{ ficha.foto.url }}" class="card-img-top" alt="Image">
                    {% else %}
                    <img src="https://via.placeholder.com/300" class="card-img-top" alt="Placeholder Image">
                    {% endif %}

                    <div class="card-body">
                        <h5 class="card-title">{{ ficha.nome }} ( {{ficha.get_nome_classe}} - Lvl: {{ ficha.nivel }} ) </h5>
                        <div class="d-grid gap-2 d-md-block">
                            <a class="btn btn-info" href='/fichas/{{ficha.id}}' type="button">Detalhes</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

grimorio/templates/fichas/novo.html
{% extends "../base.html" %}

{% block titulo %} Criar novo Personagem {% endblock %}

{% block content %}

<div class="container mt-5">
    <h1 class="mb-4">Criar novo Personagem</h1>
    <form action='/fichas/novo/' method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <div class="alert alert-danger mt-2">
                        {% for error in field.errors %}
                            <p class="mb-0">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Criar</button>
    </form>
</div>

{% endblock %}